- name: RHEL | Set version specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - always

- name: RHEL | Install {{ firewall_name }} and libselinux-python
  yum:
    name:
      - libselinux-python
      - "{{ firewall_name }}"
    state: present
  tags:
    - common

- name: RHEL | Enable specific firewall ports
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: enabled
  with_items: "{{ firewall_ports }}"
  notify: restart firewalld

- name: RHEL | Start firewalld
  service:
    name: "{{ firewalld_service }}"
    state: started
#- name: RHEL | Stop and disable firewall
#  service:
#    name: "{{ firewall_name }}"
#    state: stopped
#  tags:
#    - common
